config/routes.rb
Rails.application.routes.draw do
  #Employees record related routes
  root "employee#index"
  post '/employee/update/:id'=> 'employee#update', as: 'update_employee'
  get 'employee_contact_information/new'=> 'employee_contact_information#new', as: 'new_employee_contact_information'
  get 'employee_contact_information/destroy/:id'=> 'employee_contact_information#destroy', as: 'destroy_employee_contact_information'
  post 'employee_contact_information/create'=> 'employee_contact_information#create', as: 'create_employee_contact_information'
  # devise_for :employees
  devise_for :employees, controllers: {
  sessions: 'employees/sessions',
  registrations: 'employees/registrations'
}
  
  #payment record related routes
  get 'payment_records/index'
  get 'payment_record/new/:id'=> 'payment_records#new', as: 'new_payment_record'
  get 'payment_record/destroy'=> 'payment_records#destroy', as: 'destroy_payment_record'
  post 'payment_record/create/:id'=> 'payment_records#create', as: 'create_payment_record'

  # subscription record related routes
  get 'subscription_records'=> 'subscription_records#index', as: 'subscription_records'
  get 'filtered_subscription_records'=> 'subscription_records#filter', as: 'filtered_subscription_records'
  get 'unpaid_subscription_records'=> 'subscription_records#unpaid', as: 'unpaid_subscription_records'
  get 'subscription_record/history'=> 'subscription_records#history', as: 'subscription_record_history'
  get 'subscription_record/new'=> 'subscription_records#new', as: 'new_subscription_record'
  post 'subscription_record/create'=> 'subscription_records#create', as: 'create_subscription_record'
  get '/subscription_record/delete/:id' => 'subscription_records#destroy', as: 'destroy_subscription_record'
  get '/subscription_record/edit/:id' => 'subscription_records#edit', as: 'edit_subscription_record'
  post '/subscription_record/update/:id' => 'subscription_records#update', as: 'update_subscription_record'
  post '/subscription_record/assign_employees' => 'subscription_records#assign_employees', as: 'assign_employees'

  # subscription type related routes
  get '/subscription_types/delete/:id' => 'subscription_types#destroy', as: 'destroy_subscription_type'
  post '/subscription_types/update/:id' => 'subscription_types#update', as: 'update_subscription_type'
  get '/subscription_types/edit/:id' => 'subscription_types#edit', as: 'edit_subscription_type'
  resources :subscription_types
  
  # client related routes
  get '/clients' => 'clients#index', as: 'clients'
  get '/client_history' => 'clients#history', as: 'client_history'
  get '/client/new' => 'clients#new', as: 'new_client'
  post '/client/create' => 'clients#create', as: 'create_client'
  get '/client/delete/:id' => 'clients#destroy', as: 'destroy_client'
  post '/client/update/:id' => 'clients#update', as: 'update_client'
  get '/client/edit/:id' => 'clients#edit', as: 'edit_client'
  get '/client_contact_information/destroy/:id'=> 'client_contact_information#destroy', as: 'destroy_client_contact_information'
  post '/client_contact_information/create'=> 'client_contact_information#create', as: 'create_client_contact_information'
 
  get 'employee/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  get 'download', to: 'backups#download'
  get 'download_subscription_types_as_csv' => 'backups#download_subscription_types_as_csv', as: 'download_subscription_types_as_csv'
  get 'download_subscription_records_as_csv' => 'backups#download_subscription_records_as_csv', as: 'download_subscription_records_as_csv'
  get 'download_payment_records_as_csv' => 'backups#download_payment_records_as_csv', as: 'download_payment_records_as_csv'
  get 'download_clients_as_csv' => 'backups#download_clients_as_csv', as: 'download_clients_as_csv'

  #Activity related routes
  get 'activities/index' => 'activity#index', as: 'activirties'

  # Report related routes
  get 'reports/get_daily_report' => 'report#get_daily_report', as: 'get_daily_report'
  get 'reports/get_monthly_report' => 'report#get_monthly_report', as: 'get_monthly_report'

  # test related routes
  get 'test' => 'test#test', as: 'test'

  # Agent related routes
  get 'agents/get_agents' => 'agents#get_agents', as: 'get_agents' 
  get 'agents/create_agent' => 'agents#create', as: 'create_agent'
  get 'agents/destroy_agent' => 'agents#destroy', as: 'destroy_agent'
  get 'agents/update_agent' => 'agents#update', as: 'update_agent'

  # Company related routes
  get 'comanies/get_comanies' => 'company#get_companies', as: 'get_companies' 
  get 'comanies/create_company' => 'company#create', as: 'create_company'
  get 'companies/destroy_company' => 'company#destroy', as: 'destroy_company'
  get 'companies/update_company' => 'company#update', as: 'update_company'

  # Ledger related routes
  get 'ledgers/get_ledgers' => 'ledger#get_ledgers', as: 'get_ledgers' 
  get 'ledgers/create_ledger' => 'ledger#create', as: 'create_ledger'
  get 'ledgers/destroy_ledger' => 'ledger#destroy', as: 'destroy_ledger'
  get 'ledgers/add_to_deposit' => 'ledger#add_to_deposit', as: 'add_to_deposit'
  get 'ledgers/update_ledger' => 'ledger#update', as: 'update_ledger'
  get 'ledgers/agent_history' => 'ledger#history', as: 'agent_history'
  
end

app/models/client.rb
class Client < ApplicationRecord

    after_create :save_new_record_to_activity
    after_destroy :save_deleted_record_to_activity
    after_update :save_record_changes_to_activity

    has_many :client_contact_informations, dependent: :destroy
    accepts_nested_attributes_for :client_contact_informations
    has_many :subscription_records, dependent: :destroy
    
    validates_associated :client_contact_informations
    validates_associated :subscription_records
    validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 30 }
    validates :username, uniqueness: true, length: { minimum: 3, maximum: 30 }

    private

    def save_new_record_to_activity
        json_data = {
            name: self.name,
            username: self.username,
            coordinate: self.coordinate,
            created_at: self.created_at,
            updated_at: self.updated_at,
        }
        create_activity_record(action_type: 'create' ,table_name: 'client' ,json_data: json_data)
    end

    def save_deleted_record_to_activity
        json_data = {
            name: self.name,
            username: self.username,
            coordinate: self.coordinate,
            created_at: self.created_at,
            updated_at: self.updated_at,
        }
        create_activity_record(action_type: 'delete' ,table_name: 'client' ,json_data: json_data)
    end

    def save_record_changes_to_activity
        changes_made = self.saved_changes
        json_data = {
                name: self.name,
                username: self.username,
                coordinate: self.coordinate,
                created_at: self.created_at,
                updated_at: self.updated_at,
        }
        merged_hash = json_data.merge(changes_made)
        create_activity_record(action_type: 'update' ,table_name: 'client' ,json_data: merged_hash)
    end

    def create_activity_record( action_type: ,table_name: ,json_data: )
        Activity.create(
            employee_name: Current.employee.name,
            action_type: action_type,
            table_name: table_name,
            json_data: json_data.to_json
        )
    end

    
    
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  def index
    @clients = Client.all.includes(:client_contact_informations)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @clients = Client.order(created_at: :desc).includes(:client_contact_informations)
    render json: @clients, include: { client_contact_informations: { only: [:id, :contact_info] } }
  end
  
  def new
    @new_client = Client.new
  end

  def create
    name = params[:new_client][:name]
    username = params[:new_client][:username]
    contact_info = params[:new_client][:contact_info]
    info = params[:new_client][:info]
    coordinate = params[:new_client][:coordinate]
    
    @new_client = Client.new(name: name, username: username,info: info, coordinate: coordinate)
    if @new_client.save 
      @contact_info = ClientContactInformation.create(client: @new_client, contact_info: contact_info)
      # render json: @new_client.as_json(include: { client_contact_informations: { only: [:contact_info] } })
      # render json: { client: @new_client, contact_info: @contact_info}, status: 200
      render json: @new_client, include: { client_contact_informations: { only: [:id, :contact_info] } }, status: 200
    else
      render json: { message: "error" }, status: 400
    end
  end

  def destroy
    @client = Client.find(params[:id])
    if @client.destroy
      render json: {client_id: params[:id]}, status: 200
    else
      render json: {message: 'error'}, status: 400
    end  
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update

    # @client = Client.find(params[:id])
    # if @client.update(updated_client_params)
    #   redirect_to clients_path
    # else
    #   redirect_to edit_client_path(@client)
    # end
    name = params[:updated_client][:name]
    username = params[:updated_client][:username]
    coordinate = params[:updated_client][:coordinate]
    info = params[:updated_client][:info]
  
    # Access nested attribute values using the association name
    # contact_info = params[:updated_client][:contact_info]
    @client = Client.find(params[:id])

    if @client.update(name: name, username: username, coordinate: coordinate, info: info)
      #  @client.client_contact_informations.first.update(contact_info: contact_info)
      # Successful update, do something (e.g., redirect to the record's page)
      client = @client.as_json(include: { client_contact_informations: { only: [:id, :contact_info] } })
      render json: {message: 'success', client: client }, status: 200
    else
      # Failed update, render the edit form again with error messages
      render json: {message: 'error'}, status: 400
    end
  end

  def history
    id =params[:id]
    client = Client.find(id)
    subscription_records = client.subscription_records.order(created_at: :desc).as_json(include: { 
      client: { only: [:name] }, 
      employee: { only: [:name] }, 
      subscription_type: { only: [:category, :cost] } 
    })

    render json: subscription_records

  end

  private

  def client_params
    params.require(:new_client).permit(:name, :username, :contact_info, :coordinate)
  end

  def updated_client_params
    params.require(:updated_client).permit(:name, :username, :contact_info, :coordinate)
  end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/edit.html.erb
<h1>Edit Client</h1>
<div class="container p-3 d-flex flex-column align-items-stretch">
<%= form_with model: @client, url: update_client_path(id: params[:id]), method: :post, local: true, scope: :updated_client do |f| %>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= f.label :username %><br>
      <%= f.text_field :username, class: "form-control" %>
    </div>
  
    <%= f.fields_for :client_contact_informations do |contact_fields| %>
      <div class="form-group">
        <%= contact_fields.label :'Contact information' %><br>
        <%= contact_fields.text_field :contact_info, class: "form-control" %>
      </div>
    <% end %>
  
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/clients/index.html.erb
<h1>Client#index</h1>
<p>Find me in app/views/client/index.html.erb</p>
<div class="container">
    <div class="row justify-content-center">
        <table class="table table-striped table-bordered w-75 ">
            <thead class="thead-dark">
                <tr>
                <th>Name</th>
                <th>username</th>
                <th>Contact info</th>
                <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @clients.each do |client| %>
                <tr>
                    <td><%= client.name %></td>
                    <td><%= client.username %></td>
                    <td>
                        <% if client.client_contact_informations.first.try(:contact_info).present? %>
                         <%= client.client_contact_informations.first.contact_info %>
                        <% else %>
                         No contact information
                        <% end %>
                    </td>
                    <td>
                      <%= link_to 'Delete', destroy_client_path(client), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                      <%= link_to "Edit", edit_client_path(client), class: "btn btn-primary" %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>
<%= link_to "Create new Client", new_client_path, class: "btn btn-primary" %>

app/views/clients/new.html.erb
<h1>Create new client</h1>
<div class="container p-3 d-flex flex-column align-items-stretch">
<%= form_with model: @new_client, url: create_client_path, method: :post, local: true, scope: :new_client do |f| %>
    <div class="form-group">
    <%= f.label :Name %><br>
    <%= f.text_field :name,class:"form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :'User name' %><br>
    <%= f.text_field :username,class:"form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :'Contact information' %><br>
    <%= f.text_field :contact_info,class:"form-control" %>
    </div>

    <%= f.submit "Save",class:"btn btn-primary" %>
<% end %>
</div>