config/routes.rb
Rails.application.routes.draw do
  #Employees record related routes
  root "employee#index"
  post '/employee/update/:id'=> 'employee#update', as: 'update_employee'
  get 'employee_contact_information/new'=> 'employee_contact_information#new', as: 'new_employee_contact_information'
  get 'employee_contact_information/destroy/:id'=> 'employee_contact_information#destroy', as: 'destroy_employee_contact_information'
  post 'employee_contact_information/create'=> 'employee_contact_information#create', as: 'create_employee_contact_information'
  # devise_for :employees
  devise_for :employees, controllers: {
  sessions: 'employees/sessions',
  registrations: 'employees/registrations'
}
  
  #payment record related routes
  get 'payment_records/index'
  get 'payment_record/new/:id'=> 'payment_records#new', as: 'new_payment_record'
  get 'payment_record/destroy'=> 'payment_records#destroy', as: 'destroy_payment_record'
  post 'payment_record/create/:id'=> 'payment_records#create', as: 'create_payment_record'

  # subscription record related routes
  get 'subscription_records'=> 'subscription_records#index', as: 'subscription_records'
  get 'filtered_subscription_records'=> 'subscription_records#filter', as: 'filtered_subscription_records'
  get 'unpaid_subscription_records'=> 'subscription_records#unpaid', as: 'unpaid_subscription_records'
  get 'subscription_record/history'=> 'subscription_records#history', as: 'subscription_record_history'
  get 'subscription_record/new'=> 'subscription_records#new', as: 'new_subscription_record'
  post 'subscription_record/create'=> 'subscription_records#create', as: 'create_subscription_record'
  get '/subscription_record/delete/:id' => 'subscription_records#destroy', as: 'destroy_subscription_record'
  get '/subscription_record/edit/:id' => 'subscription_records#edit', as: 'edit_subscription_record'
  post '/subscription_record/update/:id' => 'subscription_records#update', as: 'update_subscription_record'
  post '/subscription_record/assign_employees' => 'subscription_records#assign_employees', as: 'assign_employees'

  # subscription type related routes
  get '/subscription_types/delete/:id' => 'subscription_types#destroy', as: 'destroy_subscription_type'
  post '/subscription_types/update/:id' => 'subscription_types#update', as: 'update_subscription_type'
  get '/subscription_types/edit/:id' => 'subscription_types#edit', as: 'edit_subscription_type'
  resources :subscription_types
  
  # client related routes
  get '/clients' => 'clients#index', as: 'clients'
  get '/client_history' => 'clients#history', as: 'client_history'
  get '/client/new' => 'clients#new', as: 'new_client'
  post '/client/create' => 'clients#create', as: 'create_client'
  get '/client/delete/:id' => 'clients#destroy', as: 'destroy_client'
  post '/client/update/:id' => 'clients#update', as: 'update_client'
  get '/client/edit/:id' => 'clients#edit', as: 'edit_client'
  get '/client_contact_information/destroy/:id'=> 'client_contact_information#destroy', as: 'destroy_client_contact_information'
  post '/client_contact_information/create'=> 'client_contact_information#create', as: 'create_client_contact_information'
 
  get 'employee/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  get 'download', to: 'backups#download'
  get 'download_subscription_types_as_csv' => 'backups#download_subscription_types_as_csv', as: 'download_subscription_types_as_csv'
  get 'download_subscription_records_as_csv' => 'backups#download_subscription_records_as_csv', as: 'download_subscription_records_as_csv'
  get 'download_payment_records_as_csv' => 'backups#download_payment_records_as_csv', as: 'download_payment_records_as_csv'
  get 'download_clients_as_csv' => 'backups#download_clients_as_csv', as: 'download_clients_as_csv'

  #Activity related routes
  get 'activities/index' => 'activity#index', as: 'activirties'

  # Report related routes
  get 'reports/get_daily_report' => 'report#get_daily_report', as: 'get_daily_report'
  get 'reports/get_monthly_report' => 'report#get_monthly_report', as: 'get_monthly_report'

  # test related routes
  get 'test' => 'test#test', as: 'test'

  # Agent related routes
  get 'agents/get_agents' => 'agents#get_agents', as: 'get_agents' 
  get 'agents/create_agent' => 'agents#create', as: 'create_agent'
  get 'agents/destroy_agent' => 'agents#destroy', as: 'destroy_agent'
  get 'agents/update_agent' => 'agents#update', as: 'update_agent'

  # Company related routes
  get 'comanies/get_comanies' => 'company#get_companies', as: 'get_companies' 
  get 'comanies/create_company' => 'company#create', as: 'create_company'
  get 'companies/destroy_company' => 'company#destroy', as: 'destroy_company'
  get 'companies/update_company' => 'company#update', as: 'update_company'

  # Ledger related routes
  get 'ledgers/get_ledgers' => 'ledger#get_ledgers', as: 'get_ledgers' 
  get 'ledgers/create_ledger' => 'ledger#create', as: 'create_ledger'
  get 'ledgers/destroy_ledger' => 'ledger#destroy', as: 'destroy_ledger'
  get 'ledgers/add_to_deposit' => 'ledger#add_to_deposit', as: 'add_to_deposit'
  get 'ledgers/update_ledger' => 'ledger#update', as: 'update_ledger'
  get 'ledgers/agent_history' => 'ledger#history', as: 'agent_history'
  
end

app/controllers/subscription_type_controller.rb
class SubscriptionTypeController < ApplicationController
  def index
    @subscription_types = SubscriptionType.all
  end

  def new
    @new_subscription_type = SubscriptionType.new
  end

  def destroy
    @subscription_type = SubscriptionType.find(params[:id])
    @subscription_type.destroy

    redirect_to subscription_type_index_path, notice: "User was successfully deleted."
  end

  
  def create
    @new_subscription_type = SubscriptionType.new(subscription_type_params)
    if @new_subscription_type.save
      redirect_to subscription_type_index_path
    else
      redirect_to :new
    end
  end

  private

  def subscription_type_params
    params.require(:new_subscription_type).permit(:category, :cost, :profit)
  end
end

app/controllers/subscription_types_controller.rb
class SubscriptionTypesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @subscription_types = SubscriptionType.all
    render json: @subscription_types
  end

  def new
    @new_subscription_type = SubscriptionType.new
  end

  def destroy
    @subscription_type = SubscriptionType.find(params[:id])
    if @subscription_type.destroy
      render json: {subscription_type_id: params[:id]}, status: 200
    else
      render json: {message: 'error'}, status: 400
    end  
  end

  
  def create
      @new_subscription_type = SubscriptionType.new(subscription_type_params)
      if @new_subscription_type.save
        render json: { message: "success", subscription_type: @new_subscription_type }, status: 200
      else
        render json: { message: "error" }, status: 400
      end
  end

  def edit
    @subscription_type = SubscriptionType.find(params[:id])
  end

  def update
    @subscription_type = SubscriptionType.find(params[:id])

    if @subscription_type.update(subscription_type_params)
      # Successful update, do something (e.g., redirect to the record's page)
      render json: { message: "success", subscription_type: @subscription_type }, status: 200
    else
      # Failed update, render the edit form again with error messages
      render json: { message: "error" }, status: 400
    end
  end

  private

  def subscription_type_params
    params.require(:new_subscription_type).permit(:category, :cost, :profit)
  end
end

app/helpers/subscription_type_helper.rb
module SubscriptionTypeHelper
end

app/views/subscription_types/edit.html.erb
<h1>Edit subscription type</h1>
<div class="container p-3 d-flex flex-column align-items-stretch">
<%= form_with model: @subscription_type, url: update_subscription_type_path(id: params[:id]), method: :post, local: true, scope: :new_subscription_type do |f| %>
    <div class="form-group">
        <%= f.label :Type %><br>
        <%= f.text_field :category,class:"form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :Cost %><br>
    <%= f.number_field  :cost, class:"form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :Profit %><br>
    <%= f.number_field  :profit,class:"form-control"%>
    </div>

    <%= f.submit "Save",class:"btn btn-primary" %>
<% end %>
</div>

app/views/subscription_types/index.html.erb
<h1>SubscriptionType#index</h1>
<p>Find me in app/views/subscription_type/index.html.erb</p>
<div class="container">
    <div class="row justify-content-center">
        <table class="table table-striped table-bordered w-75 ">
            <thead class="thead-dark">
                <tr>
                <th>Type</th>
                <th>Cost</th>
                <th>Profit info</th>
                <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @subscription_types.each do |subscription_type| %>
                <tr>
                    <td><%= subscription_type.category %></td>
                    <td><%= subscription_type.cost %></td>
                    <td><%= subscription_type.profit %></td>
                    <td>
                      <%= link_to 'Delete', destroy_subscription_type_path(subscription_type), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                      <%= link_to "Edit", edit_subscription_type_path(id: subscription_type.id), class: "btn btn-primary" %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>
<%= link_to "Create new subscription type", new_subscription_type_path, class: "btn btn-primary" %>

app/views/subscription_types/new.html.erb
<div class="container p-3 d-flex flex-column align-items-stretch">
<%= form_with model: @new_subscription_type, url: subscription_types_create_path, method: :post, local: true, scope: :new_subscription_type do |f| %>
    <div class="form-group">
    <%= f.label :Type %><br>
    <%= f.text_field :category,class:"form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :Cost %><br>
    <%= f.number_field  :cost,class:"form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :Profit %><br>
    <%= f.number_field  :profit,class:"form-control"%>
    </div>

    <%= f.submit "Save",class:"btn btn-primary" %>
<% end %>
</div>