config/routes.rb
Rails.application.routes.draw do
  #Employees record related routes
  root "employee#index"
  post '/employee/update/:id'=> 'employee#update', as: 'update_employee'
  get 'employee_contact_information/new'=> 'employee_contact_information#new', as: 'new_employee_contact_information'
  get 'employee_contact_information/destroy/:id'=> 'employee_contact_information#destroy', as: 'destroy_employee_contact_information'
  post 'employee_contact_information/create'=> 'employee_contact_information#create', as: 'create_employee_contact_information'
  # devise_for :employees
  devise_for :employees, controllers: {
  sessions: 'employees/sessions',
  registrations: 'employees/registrations'
}
  
  #payment record related routes
  get 'payment_records/index'
  get 'payment_record/new/:id'=> 'payment_records#new', as: 'new_payment_record'
  get 'payment_record/destroy'=> 'payment_records#destroy', as: 'destroy_payment_record'
  post 'payment_record/create/:id'=> 'payment_records#create', as: 'create_payment_record'

  # subscription record related routes
  get 'subscription_records'=> 'subscription_records#index', as: 'subscription_records'
  get 'filtered_subscription_records'=> 'subscription_records#filter', as: 'filtered_subscription_records'
  get 'unpaid_subscription_records'=> 'subscription_records#unpaid', as: 'unpaid_subscription_records'
  get 'subscription_record/history'=> 'subscription_records#history', as: 'subscription_record_history'
  get 'subscription_record/new'=> 'subscription_records#new', as: 'new_subscription_record'
  post 'subscription_record/create'=> 'subscription_records#create', as: 'create_subscription_record'
  get '/subscription_record/delete/:id' => 'subscription_records#destroy', as: 'destroy_subscription_record'
  get '/subscription_record/edit/:id' => 'subscription_records#edit', as: 'edit_subscription_record'
  post '/subscription_record/update/:id' => 'subscription_records#update', as: 'update_subscription_record'
  post '/subscription_record/assign_employees' => 'subscription_records#assign_employees', as: 'assign_employees'

  # subscription type related routes
  get '/subscription_types/delete/:id' => 'subscription_types#destroy', as: 'destroy_subscription_type'
  post '/subscription_types/update/:id' => 'subscription_types#update', as: 'update_subscription_type'
  get '/subscription_types/edit/:id' => 'subscription_types#edit', as: 'edit_subscription_type'
  resources :subscription_types
  
  # client related routes
  get '/clients' => 'clients#index', as: 'clients'
  get '/client_history' => 'clients#history', as: 'client_history'
  get '/client/new' => 'clients#new', as: 'new_client'
  post '/client/create' => 'clients#create', as: 'create_client'
  get '/client/delete/:id' => 'clients#destroy', as: 'destroy_client'
  post '/client/update/:id' => 'clients#update', as: 'update_client'
  get '/client/edit/:id' => 'clients#edit', as: 'edit_client'
  get '/client_contact_information/destroy/:id'=> 'client_contact_information#destroy', as: 'destroy_client_contact_information'
  post '/client_contact_information/create'=> 'client_contact_information#create', as: 'create_client_contact_information'
 
  get 'employee/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  get 'download', to: 'backups#download'
  get 'download_subscription_types_as_csv' => 'backups#download_subscription_types_as_csv', as: 'download_subscription_types_as_csv'
  get 'download_subscription_records_as_csv' => 'backups#download_subscription_records_as_csv', as: 'download_subscription_records_as_csv'
  get 'download_payment_records_as_csv' => 'backups#download_payment_records_as_csv', as: 'download_payment_records_as_csv'
  get 'download_clients_as_csv' => 'backups#download_clients_as_csv', as: 'download_clients_as_csv'

  #Activity related routes
  get 'activities/index' => 'activity#index', as: 'activirties'

  # Report related routes
  get 'reports/get_daily_report' => 'report#get_daily_report', as: 'get_daily_report'
  get 'reports/get_monthly_report' => 'report#get_monthly_report', as: 'get_monthly_report'

  # test related routes
  get 'test' => 'test#test', as: 'test'

  # Agent related routes
  get 'agents/get_agents' => 'agents#get_agents', as: 'get_agents' 
  get 'agents/create_agent' => 'agents#create', as: 'create_agent'
  get 'agents/destroy_agent' => 'agents#destroy', as: 'destroy_agent'
  get 'agents/update_agent' => 'agents#update', as: 'update_agent'

  # Company related routes
  get 'comanies/get_comanies' => 'company#get_companies', as: 'get_companies' 
  get 'comanies/create_company' => 'company#create', as: 'create_company'
  get 'companies/destroy_company' => 'company#destroy', as: 'destroy_company'
  get 'companies/update_company' => 'company#update', as: 'update_company'

  # Ledger related routes
  get 'ledgers/get_ledgers' => 'ledger#get_ledgers', as: 'get_ledgers' 
  get 'ledgers/create_ledger' => 'ledger#create', as: 'create_ledger'
  get 'ledgers/destroy_ledger' => 'ledger#destroy', as: 'destroy_ledger'
  get 'ledgers/add_to_deposit' => 'ledger#add_to_deposit', as: 'add_to_deposit'
  get 'ledgers/update_ledger' => 'ledger#update', as: 'update_ledger'
  get 'ledgers/agent_history' => 'ledger#history', as: 'agent_history'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ISPManagmentSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid">
    <div class="row">
    <% if employee_signed_in? %>
      <div class="col-sm-3 bg-light sidebar">
        <h3>Welcome <%= current_employee.name %></h3>
        <hr>
        <ul class="list-unstyled">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Employees", root_path %></li>
          <li><%= link_to "Clients", clients_path %></li>
          <li><%= link_to "Subscription Types", subscription_types_path %></li>
          <li><%= link_to "Subscription Records", subscription_records_path %></li>
          <li><%= link_to "Payment Records", payment_records_index_path %></li>
          <li><%= link_to "Settings", root_path %></li>
        </ul>
        <%= button_to "logout", destroy_employee_session_path, method: :delete,class:"btn btn-light" %>
      </div>
      <% end %>
      <div class=<%= employee_signed_in?? "col-sm-9":"col-sm-12" %>>
        <%= yield %>
      </div>
    </div>
 
  
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>